name: CI/CD

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]
    tags:
      - "**"

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run unit tests
        shell: bash
        run: |
          # Run system checks
          python manage.py check

          # Check for missing migrations
          python manage.py makemigrations --check --noinput

          # Run tests
          python manage.py test
